import type {
  Conversation,
  Followup,
  Lead,
  OutreachItem,
  Prospect,
  Quote,
} from "./types";

const today = new Date().toISOString().slice(0, 10);
export const conversations: Conversation[] = [
  {
    id: "conv-farmacia",
    name: "María Rodríguez",
    business: "Farmacia Central",
    phone: "+506 8701 2240",
    status: "ACTIVE",
    agentMode: "AUTO",
    unread: 3,
    lastMessage: "¿Pueden automatizar los pedidos?",
    lastMessageAt: "12:41",
    category: "Farmacia",
    city: "San Vito",
    leadStatus: "INTERESTED",
    score: 92,
    interest: "Automatización",
    source: "WhatsApp",
    objective: "Gestionar consultas y pedidos por WhatsApp",
    notes: "Tiene dos sucursales y alto volumen de consultas.",
    messages: [
      {
        id: "m1",
        direction: "in",
        body: "Hola, vi sus servicios de automatización.",
        at: "12:35",
        author: "Cliente",
      },
      {
        id: "m2",
        direction: "out",
        body: "¡Hola María! Claro, cuéntame cómo gestionan hoy sus pedidos.",
        at: "12:36",
        author: "Agente",
      },
      {
        id: "m3",
        direction: "in",
        body: "Todo entra por WhatsApp y lo pasamos manualmente al sistema.",
        at: "12:39",
        author: "Cliente",
      },
      {
        id: "m4",
        direction: "in",
        body: "¿Pueden automatizar los pedidos?",
        at: "12:41",
        author: "Cliente",
      },
    ],
  },
  {
    id: "conv-taller",
    name: "Carlos Campos",
    business: "Taller Campos",
    phone: "+506 8812 4900",
    status: "PENDING",
    agentMode: "HUMAN",
    unread: 0,
    lastMessage: "Perfecto, quedo atento a la propuesta.",
    lastMessageAt: "11:18",
    category: "Automotriz",
    city: "Ciudad Neily",
    leadStatus: "QUOTE",
    score: 84,
    interest: "Sitio web + reservas",
    source: "Referencia",
    objective: "Captar citas sin llamadas",
    notes: "Johan tomó la conversación para preparar alcance.",
    messages: [
      {
        id: "m5",
        direction: "out",
        body: "Te envío la propuesta hoy por la tarde.",
        at: "11:16",
        author: "Johan",
      },
      {
        id: "m6",
        direction: "in",
        body: "Perfecto, quedo atento a la propuesta.",
        at: "11:18",
        author: "Cliente",
      },
    ],
  },
  {
    id: "conv-vet",
    name: "Andrea Mora",
    business: "Veterinaria Luna",
    phone: "+506 7290 1133",
    status: "NEW",
    agentMode: "AUTO",
    unread: 1,
    lastMessage: "Quiero saber sobre el sistema de citas",
    lastMessageAt: "10:52",
    category: "Veterinaria",
    city: "San Vito",
    leadStatus: "NEW",
    score: 91,
    interest: "Reservas",
    source: "Instagram",
    objective: "Reservas y recordatorios automáticos",
    notes: "Prospecto de alta prioridad.",
    messages: [
      {
        id: "m7",
        direction: "in",
        body: "Quiero saber sobre el sistema de citas",
        at: "10:52",
        author: "Cliente",
      },
    ],
  },
  {
    id: "conv-gym",
    name: "Luis Vargas",
    business: "Gym Power",
    phone: "+506 8998 6102",
    status: "ACTIVE",
    agentMode: "PAUSED",
    unread: 0,
    lastMessage: "Lo revisamos el viernes",
    lastMessageAt: "Ayer",
    category: "Fitness",
    city: "Golfito",
    leadStatus: "CONTACTED",
    score: 68,
    interest: "CRM",
    source: "Web",
    objective: "Seguimiento de membresías",
    notes: "Esperar confirmación del socio.",
    messages: [
      {
        id: "m8",
        direction: "in",
        body: "Lo revisamos el viernes",
        at: "16:20",
        author: "Cliente",
      },
    ],
  },
];

export const prospects: Prospect[] = [
  {
    id: "pros-vet",
    business: "Veterinaria Luna",
    category: "Veterinaria",
    city: "San Vito",
    phone: "+506 7290 1133",
    whatsapp: true,
    web: "",
    instagram: "@veterinarialuna",
    facebook: "Veterinaria Luna",
    score: 91,
    opportunity: "Automatización de atención y reservas",
    status: "PRIORITY",
    lastAction: "Detectado hoy",
    problems: [
      "No tiene página web",
      "WhatsApp como canal principal",
      "Reservas manuales",
      "Sin recordatorios automáticos",
    ],
    suggestedMessage:
      "Hola, Andrea. Vi que Veterinaria Luna gestiona sus citas principalmente por WhatsApp. Preparé una idea sencilla para automatizar reservas y recordatorios sin perder el trato personal. ¿Te la comparto?",
  },
  {
    id: "pros-farmacia",
    business: "Farmacia Central",
    category: "Farmacia",
    city: "San Vito",
    phone: "+506 8701 2240",
    whatsapp: true,
    web: "farmaciacentral.cr",
    instagram: "@farmaciacentral",
    facebook: "Farmacia Central",
    score: 92,
    opportunity: "Asistente para consultas y pedidos",
    status: "INTERESTED",
    lastAction: "Respondió hace 8 min",
    problems: [
      "Alto volumen de consultas",
      "Pedidos transcritos manualmente",
      "Varias sucursales",
    ],
    suggestedMessage:
      "Hola, María. Podemos conectar WhatsApp con su flujo de pedidos para responder disponibilidad y registrar solicitudes automáticamente.",
  },
  {
    id: "pros-cafe",
    business: "Café Horizonte",
    category: "Restaurante",
    city: "Buenos Aires",
    phone: "+506 8544 7821",
    whatsapp: true,
    web: "",
    instagram: "@cafehorizonte",
    facebook: "",
    score: 78,
    opportunity: "Web y menú digital",
    status: "NEW",
    lastAction: "Detectado ayer",
    problems: ["No tiene página web", "Menú solo en redes"],
    suggestedMessage:
      "Hola. Vi el trabajo de Café Horizonte y creo que un menú web rápido podría facilitar pedidos y ubicación. ¿Les muestro una propuesta?",
  },
  {
    id: "pros-hotel",
    business: "Hotel Coto",
    category: "Hotelería",
    city: "Golfito",
    phone: "+506 2775 0031",
    whatsapp: true,
    web: "hotelcoto.example",
    instagram: "",
    facebook: "Hotel Coto",
    score: 73,
    opportunity: "Reservas directas",
    status: "CONTACTED",
    lastAction: "Mensaje aprobado",
    problems: ["Web lenta", "Reservas por mensajería"],
    suggestedMessage:
      "Hola. Tengo una propuesta para simplificar sus reservas directas y reducir consultas repetidas.",
  },
];
export const leads: Lead[] = [
  {
    id: "lead-1",
    business: "Clínica Sonrisa",
    contact: "Laura Jiménez",
    value: 950,
    score: 86,
    stage: "NEW",
    lastActivity: "Hace 12 min",
  },
  {
    id: "lead-2",
    business: "Gym Power",
    contact: "Luis Vargas",
    value: 1200,
    score: 68,
    stage: "CONTACTED",
    lastActivity: "Ayer",
  },
  {
    id: "lead-3",
    business: "Veterinaria Luna",
    contact: "Andrea Mora",
    value: 1800,
    score: 91,
    stage: "REPLIED",
    lastActivity: "Hace 1 h",
  },
  {
    id: "lead-4",
    business: "Farmacia Central",
    contact: "María Rodríguez",
    value: 2800,
    score: 92,
    stage: "INTERESTED",
    lastActivity: "Hace 8 min",
  },
  {
    id: "lead-5",
    business: "Taller Campos",
    contact: "Carlos Campos",
    value: 1500,
    score: 84,
    stage: "QUOTE",
    lastActivity: "Hoy 11:18",
  },
  {
    id: "lead-6",
    business: "Eco Lodge Sur",
    contact: "Sofía Solís",
    value: 3600,
    score: 88,
    stage: "MEETING",
    lastActivity: "Hoy 09:20",
  },
];
export const quotes: Quote[] = [
  {
    id: "quote-1",
    client: "Carlos Campos",
    business: "Taller Campos",
    service: "Web + reservas",
    scope: "Sitio, catálogo de servicios y agenda",
    notes: "Incluye soporte inicial",
    estimatedPrice: 1500,
    status: "SENT",
  },
  {
    id: "quote-2",
    client: "María Rodríguez",
    business: "Farmacia Central",
    service: "Automatización WhatsApp",
    scope: "Clasificación y registro de pedidos",
    notes: "Pendiente validar API",
    estimatedPrice: 2800,
    status: "DRAFT",
  },
];
export const followups: Followup[] = [
  {
    id: "follow-1",
    client: "Andrea · Veterinaria Luna",
    reason: "Confirmar demo",
    date: today,
    time: "14:30",
    channel: "WhatsApp",
    message: "Compartir enlace de demo",
    status: "TODAY",
  },
  {
    id: "follow-2",
    client: "Carlos · Taller Campos",
    reason: "Revisar cotización",
    date: today,
    time: "16:00",
    channel: "Llamada",
    message: "Confirmar alcance",
    status: "TODAY",
  },
  {
    id: "follow-3",
    client: "Luis · Gym Power",
    reason: "Retomar decisión",
    date: "2026-10-09",
    time: "10:00",
    channel: "WhatsApp",
    message: "Consultar decisión de socios",
    status: "PENDING",
  },
];
export const outreach: OutreachItem[] = [];
export const activities = [
  { time: "12:41", text: "Cliente respondió", detail: "Farmacia Central" },
  {
    time: "12:42",
    text: "Agente clasificó como automatización",
    detail: "Score actualizado a 92",
  },
  {
    time: "12:43",
    text: "Lead actualizado a interesado",
    detail: "Farmacia Central",
  },
  { time: "12:45", text: "Johan tomó conversación", detail: "Taller Campos" },
];
